General revisions before first version release
* increase readability by commenting functions
* adding balancer statisticts (`lbw [-H] balancer stats`)
* fixed incorrect errors on getting status for sysctl services
* renamed `main()` functions to `run()` to not overlap bash internal `main()`
* removed unnecessary NAT from LAN
* fixed `iptables` wrong source string (`-s x.x.x.x`)

diff --git a/src/bin/lbw b/src/bin/lbw
--- a/src/bin/lbw
+++ b/src/bin/lbw
@@ -8,18 +8,19 @@ source "$COMMON" || exit 255
 
 
 HELP="Usage: ${__COMMAND__} [OPTIONS] OBJECT { COMMAND | help }
-OBJECT := { status | service | wan | help }
+OBJECT := { status | service | wan | balancer | help }
 OPTIONS:
-    -h, --help           Show this help
-    -d, --debug          Run in debug mode (implies -f)
-    -f, --foreground     Run in foreground mode
-    -t, --timestamp      Print timestamp in log lines
-        --trace[=FILE]   Print executed commands in a .trace file"
+    -h, --help             Show this help
+    -d, --debug            Run in debug mode (implies -f)
+    -f, --foreground       Run in foreground mode
+    -t, --timestamp        Print timestamp in log lines
+    -h, --human-readable   Print sizes in human readable format (e.g., 1KB 2GiB)
+        --trace[=FILE]     Print executed commands in a .trace file"
 
 
 do_help() {
     echo "$HELP"
-    exit
+    exit 0
 }
 
 
@@ -31,7 +32,7 @@ do_usage() {
 
 list_service_status() {
     echo "Services:"
-    do_service_list "$@" | while read LINE; do
+    do_service_list | while read LINE; do
         echo "- ${LINE}"
     done
 }
@@ -39,7 +40,7 @@ list_service_status() {
 
 list_wan_status() {
     echo "WANs:"
-    do_wan_list "$@" | while read LINE; do
+    do_wan_list | while read LINE; do
         echo "- ${LINE}"
     done
 }
@@ -53,6 +54,8 @@ do_status() {
 
 ## SERVICES
 
+# VOID get_service_pid(SERVICE): PID
+# stdout PID of SERVICE
 get_service_pid() {
     local SERVICE=${1,,}
     local PID_FILE="${RUNSTATEDIR}/lbw-${SERVICE}.pid"
@@ -73,9 +76,11 @@ get_service_pid() {
 }
 
 
+# VOID get_service_status(SERVICE): STATUS
+# stdout running STATUS of SERVICE
 get_service_status() {
     local SERVICE=${1,,}
-    local STATUS=$(systemctl is-active lbw-${SERVICE})
+    local STATUS=$(systemctl is-active lbw-${SERVICE} || :)
 
     case "$STATUS" in
     'active')
@@ -95,9 +100,11 @@ get_service_status() {
 }
 
 
+# VOID get_service_enabled(SERVICE): STATUS
+# stdout enabled STATUS of SERVICE
 get_service_enabled() {
     local SERVICE=${1,,}
-    local STATUS=$(systemctl is-enabled lbw-${SERVICE})
+    local STATUS=$(systemctl is-enabled lbw-${SERVICE} || :)
 
     case "$STATUS" in
     'enabled')
@@ -112,18 +119,20 @@ get_service_enabled() {
 }
 
 
+# VOID do_service_list(VOID): STATUS
+# stdout verbose STATUS of all services
 do_service_list() {
     local SERVICE
 
-    [[ $# -gt 0 && ${1,,} != 'all' ]] || set -- 'VRF' 'Balancer'
-
-    for SERVICE; do
+    for SERVICE in 'VRF' 'Balancer'; do
         local PID=$(get_service_pid "${SERVICE}")
         echo "${SERVICE}${PID:+[${PID}]}: $(get_service_status "${SERVICE}") ($(get_service_enabled "$SERVICE"))"
     done
 }
 
 
+# VOID do_service_start(ARGS*): VOID
+# start ARGS services (or all services if ARGS is omitted)
 do_service_start() {
     local SERVICE
 
@@ -141,6 +150,8 @@ do_service_start() {
 }
 
 
+# VOID do_service_stop(ARGS*): VOID
+# stop ARGS services (or all services if ARGS is omitted)
 do_service_stop() {
     local SERVICE
 
@@ -152,6 +163,8 @@ do_service_stop() {
 }
 
 
+# VOID do_service_enable(ARGS*): VOID
+# enable ARGS services (or all services if ARGS is omitted)
 do_service_enable() {
     local SERVICE
 
@@ -163,6 +176,8 @@ do_service_enable() {
 }
 
 
+# VOID do_service_disable(ARGS*): VOID
+# disable ARGS services (or all services if ARGS is omitted)
 do_service_disable() {
     local SERVICE
 
@@ -174,6 +189,8 @@ do_service_disable() {
 }
 
 
+# VOID do_service_status(ARGS*): STATUS
+# show ARGS services status (or all services if ARGS is omitted)
 do_service_status() {
     local SERVICE
 
@@ -185,8 +202,9 @@ do_service_status() {
 }
 
 
+# VOID do_service(ARGS*): VOID
+# exec service specific command ('list' if ARGS is omitted)
 do_service() {
-    local SERVICE
     local CMD='list'
     local HELP="Usage: ${__COMMAND__} service { COMMAND }
 COMMAND:
@@ -202,11 +220,9 @@ SERVICE:
     VRF                           Virtual Routing and Forwarding service
     Balancer                      Balancer service"
 
-    if [[ $# -gt 0 ]]; then
-        CMD=$1
-        shift
-    fi
+    test $# -eq 0 || { CMD=$1 && shift; }
 
+    local SERVICE
     for SERVICE in "$@"; do
         case "${SERVICE,,}" in
         'vrf'|'balancer');;
@@ -216,7 +232,8 @@ SERVICE:
     done
 
     if [[ x'list' == x${CMD}* ]]; then
-        do_service_list "$@"
+        test $# -eq 0 || fatal "garbage command options \`$*'"
+        do_service_list
     elif [[ x'start' == x${CMD} ]]; then
         do_service_start "$@"
     elif [[ x'stop' == x${CMD} ]]; then
@@ -264,11 +281,13 @@ do_wan_list() {
     while read PROVIDER ETHERNET WEIGHT PING_IPS; do
         local TABLE_NAME=${PROVIDER,,}
         read LOSS RTT STATE < <(get_wan_status "$PROVIDER")
-        echo "${PROVIDER}: $(color_state "$STATE") (failures: $(color_loss "$LOSS"), latency: ${RTT})"
+        echo "${PROVIDER}: $(color_state "$STATE") (weight: ${WEIGHT}, failures: $(color_loss "$LOSS"), latency: ${RTT})"
     done <<<"$WAN_CONF"
 }
 
 
+# VOID do_wan(ARGS*): VOID
+# exec WAN specific command ('list' if ARGS is omitted)
 do_wan() {
     local CMD='list'
     local HELP="Usage: ${__COMMAND__} wan { COMMAND }
@@ -276,21 +295,138 @@ COMMAND:
     help               Show this help
     list               List WANs and brief status"
 
-    if [[ $# -gt 0 ]]; then
-        CMD=$1
-        shift
-    fi
+    test $# -eq 0 || { CMD=$1 && shift; }
 
     if [[ x'list' == x${CMD}* ]]; then
-        do_wan_list "$@"
+        test $# -eq 0 || fatal "garbage command options \`$*'"
+        do_wan_list
+    elif [[ x'help' == x${CMD}* ]]; then
+        do_help
     else
         fatal "Command \`${CMD}' is unknown, try \`${__COMMAND__} wan help'"
     fi
 }
 
 
+## Balancer
+
+do_balancer_stats_show() {
+    local OUT=('Service:Weight:RX Bytes:RX Pkts:TX Bytes:TX Pkts:Total Bytes:Total Pkts')
+    local TOT=(0 0 0 0 0 0)
+    local EPOCH=$(date +%s)
+    declare -A VAL
+
+    while read PROVIDER ETHERNET WEIGHT PING_IPS; do
+        local rx_bytes rx_packets tx_bytes tx_packets
+        local RX_BYTES RX_PACKETS TX_BYTES TX_PACKETS
+        local STATS=('rx_bytes' 'rx_packets' 'tx_bytes' 'tx_packets')
+
+        get_eth_stats "$ETHERNET"
+
+        # get the smallest epoch within providers
+        [[ $epoch -ge $EPOCH ]] || EPOCH=$epoch
+
+        for STAT in ${STATS[@]}; do
+            read ${STAT^^} <<<$[$(read_eth_stat "$ETHERNET" "$STAT") - ${!STAT}]
+        done
+
+        local B_T=$[RX_BYTES+TX_BYTES]
+        local P_T=$[RX_PACKETS+TX_PACKETS]
+
+        TOT=($[${TOT[0]}+$RX_BYTES] $[${TOT[1]}+$RX_PACKETS] $[${TOT[2]}+$TX_BYTES] $[${TOT[3]}+$TX_PACKETS] $[${TOT[4]}+$B_T] $[${TOT[5]}+$P_T])
+        VAL[$PROVIDER]="$RX_BYTES:$RX_PACKETS:$TX_BYTES:$TX_PACKETS:$B_T:$P_T"
+        if [[ "$HUMAN" ]]; then
+            RX_BYTES="$(numfmt --to=iec-i "$RX_BYTES")B"
+            RX_PACKETS="$(numfmt --to=si "$RX_PACKETS")"
+            TX_BYTES="$(numfmt --to=iec-i "$TX_BYTES")B"
+            TX_PACKETS="$(numfmt --to=si "$TX_PACKETS")"
+            B_T="$(numfmt --to=iec-i "$B_T")B"
+            P_T="$(numfmt --to=si "$P_T")"
+        fi
+        OUT+=("${PROVIDER}:${WEIGHT}:${RX_BYTES}:${RX_PACKETS}:${TX_BYTES}:${TX_PACKETS}:${B_T}:${P_T}")
+    done <<<"$WAN_CONF"
+
+    local PER=('' '' '' '' '' '' '' '')
+    while read PROVIDER ETHERNET WEIGHT PING_IPS; do
+        PER[0]="${PER[0]:+${PER[0]}/}%"
+        for ((i=0;i<${#TOT[@]};i++)); do
+            IFS=':' read -r -a V <<<"${VAL[$PROVIDER]}"
+            PER[$i+2]="${PER[i+2]:+${PER[i+2]}/}$((${V[i]}*100/${TOT[i]}))"
+        done
+    done <<<"$WAN_CONF"
+
+    if [[ "$HUMAN" ]]; then
+        TOT[0]="$(numfmt --to=iec-i "${TOT[0]}")B"
+        TOT[1]="$(numfmt --to=si "${TOT[1]}")"
+        TOT[2]="$(numfmt --to=iec-i "${TOT[2]}")B"
+        TOT[3]="$(numfmt --to=si "${TOT[3]}")"
+        TOT[4]="$(numfmt --to=iec-i "${TOT[4]}")B"
+        TOT[5]="$(numfmt --to=si "${TOT[5]}")"
+    fi
+    OUT+=($(IFS=':'; echo "${PER[*]}"))
+    OUT+=('TOTAL::'$(IFS=':'; echo "${TOT[*]}"))
+
+    column -t -s ':' <(IFS=$'\n'; echo "${OUT[*]}")
+
+    local ELAPSED=$[$(date +%s)-EPOCH]
+    local DAYS=$[ELAPSED/60/60/24]
+    echo "Elapsed time: ${DAYS} days, $(date -ud "@${ELAPSED}" +%X)"
+}
+
+
+do_balancer_stats_reset() {
+    (IFS='|'; [[ $# -gt 0 && ! "|${*,,}|" =~ '|all|' ]]) || set --
+
+    while read PROVIDER ETHERNET WEIGHT PING_IPS; do
+        for ARG; do [[ ${PROVIDER,,} == ${ARG,,} || ${ETHERNET,,} == ${ARG,,} ]] || continue 2; done
+        set_eth_stats "$ETHERNET"
+    done <<<"$WAN_CONF"
+}
+
+
+do_balancer_stats() {
+    local CMD='show'
+    local HELP="Usage: ${__COMMAND__} balancer stats { COMMAND }
+COMMAND:
+    help               Show this help
+    show               Show balancer statistics
+    reset              Reset ethernet counters"
+
+    test $# -eq 0 || { CMD=$1 && shift; }
+
+    if [[ x'show' == x${CMD}* ]]; then
+        do_balancer_stats_show "$@"
+    elif [[ x'reset' == x${CMD}* ]]; then
+        do_balancer_stats_reset "$@"
+    elif [[ x'help' == x${CMD}* ]]; then
+        do_help
+    else
+        fatal "Command \`${CMD}' is unknown, try \`${__COMMAND__} balancer stats help'"
+    fi
+}
+
+
+do_balancer() {
+    local CMD='stats'
+    local HELP="Usage: ${__COMMAND__} balancer { COMMAND }
+COMMAND:
+    help               Show this help
+    stats|statistics   Balancer statistics"
+
+    test $# -eq 0 || { CMD=$1 && shift; }
+
+    if [[ x'stats' == x${CMD}* || x'statistics' == x${CMD}* ]]; then
+        do_balancer_stats "$@"
+    elif [[ x'help' == x${CMD}* ]]; then
+        do_help
+    else
+        fatal "Command \`${CMD}' is unknown, try \`${__COMMAND__} balancer help'"
+    fi
+}
+
+
 # parse command options
-OPTS=$(getopt -o hdft --long help,debug,foreground,timestamp,trace:: -q -- "$@") || fatal "Unrecognized options"
+OPTS=$(getopt -o hdftH --long help,debug,foreground,timestamp,human-readable,trace:: -q -- "$@") || fatal "Unrecognized options"
 eval set -- "$OPTS"
 unset OPTS
 
@@ -300,6 +436,7 @@ while [[ $# -gt 0 ]]; do
     -d|--debug) export DEBUG=1;&
     -f|--foregraund) export FOREGROUND=1;;
     -t|--timestamp) export TIMESTAMP=1;;
+    -H|--human-readable) export HUMAN=1;;
     --trace)
         export TRACE=3
         test -z "$2" || export TRACE_FILE="$2"
@@ -313,8 +450,7 @@ done
 
 test $# -gt 0 || do_usage
 
-OBJ=$1
-shift
+OBJ=$1 && shift
 
 if [[ x'status' == x${OBJ}* ]]; then
     do_status "$@"
@@ -322,6 +458,8 @@ elif [[ x'service' == x${OBJ}* ]]; then
     do_service "$@"
 elif [[ x'wan' == x${OBJ}* ]]; then
     do_wan "$@"
+elif [[ x'balancer' == x${OBJ}* ]]; then
+    do_balancer "$@"
 elif [[ x'help' == x${OBJ}* ]]; then
     do_help
 else
diff --git a/src/bin/lbw-balancer b/src/bin/lbw-balancer
--- a/src/bin/lbw-balancer
+++ b/src/bin/lbw-balancer
@@ -7,16 +7,29 @@ COMMON="${LIBDIR}/common.sh"
 source "$COMMON" || exit 255
 
 
-# delete balanced routes
+# VOID setup(VOID): VOID
+# initialize
+setup() {
+    debug "Starting in debug mode"
+    set_status 'LOADING'
+}
+
+
+# VOID cleanup(VOID): VOID
+# cleanup on exit
 cleanup() {
+    trap - ERR
     debug "Cleaning default route on exit"
     cmd_no_fail ip route delete default scope global
+    clear_status
     exit
 }
 trap_pid
 trap cleanup INT TERM
 
 
+# VOID get_nexthops(VOID): NEXTHOPS
+# stdout nexthops for active WANs
 get_nexthops() {
     while read PROVIDER ETHERNET WEIGHT PING_IPS; do
         local TABLE_NAME=${PROVIDER,,}
@@ -35,11 +48,8 @@ get_nexthops() {
 }
 
 
-setup() {
-    debug "Starting in debug mode"
-}
-
-
+# INT check_service(SERVICE*): VOID
+# check if specific lbw-SERVICE is running
 check_service() {
     local ERR=0
 
@@ -62,12 +72,15 @@ check_service() {
 }
 
 
-main() {
+# VOID run(VOID): VOID
+# main function
+run() {
     local OLD_ROUTES OLD_DEFAULT
     local OLD_ROUTES_IPV6 OLD_DEFAULT_IPV6
     local NEW_VRF_STATUS OLD_VRF_STATUS='UNKNOWN'
     local NEW_MONITOR_STATUS OLD_MONITOR_STATUS='UNKNOWN'
 
+    set_status 'RUNNING'
     while sleep $CHECK_INTERVAL; do
         check_service 'VRF' || continue
 
@@ -113,5 +126,5 @@ main() {
 
 
 setup
-main
+run
 cleanup
diff --git a/src/bin/lbw-vrf b/src/bin/lbw-vrf
--- a/src/bin/lbw-vrf
+++ b/src/bin/lbw-vrf
@@ -7,6 +7,7 @@ COMMON="${LIBDIR}/common.sh"
 source "$COMMON" || exit 255
 
 
+# VOID setup(VOID): VOID
 # initialize
 setup() {
     debug "Starting in debug mode"
@@ -17,6 +18,7 @@ setup() {
 }
 
 
+# VOID cleanup(VOID): VOID
 # cleanup on exit
 cleanup() {
     trap - ERR
@@ -24,8 +26,9 @@ cleanup() {
     local INTERFACES=$(awk '{ print $2 }' <<<"$WAN_CONF")
 
     # iptables
+    debug "Cleaning iptables on exit"
     if bool "$IPTABLES"; then
-        for INT in $LAN_INT $INTERFACES; do
+        for INT in $INTERFACES; do
             log "Cleaning nat for interface ${INT}"
             cmd_no_fail iptables -t nat -D POSTROUTING ${LAN_NET:+-s $LAN_NET} -o $INT -j MASQUERADE
             if bool "$IPV6"; then
@@ -35,6 +38,7 @@ cleanup() {
     fi
 
     # networking
+    debug "Cleaning networking on exit"
     while read PROVIDER ETHERNET WEIGHT PING_IPS; do
         local TABLE_NAME=${PROVIDER,,}
         for PRIORITY in $(ip rule show lookup "$TABLE_NAME" | awk -F: '{ print $1 }'); do
@@ -55,6 +59,8 @@ cleanup() {
         cmd_no_fail ip route flush table "$TABLE_NAME"
         local RT_TABLE="/etc/iproute2/rt_tables.d/${TABLE_NAME}.conf"
         test -f "$RT_TABLE" && rm -f "$RT_TABLE" || :
+        local STATS_FILE="${RUNSTATEDIR}/lbw-${ETHERNET}.stats"
+        test -f "$STATS_FILE" && rm -f "$STATS_FILE" || :
         #if_up "$ETHERNET"
     done <<<"$WAN_CONF"
     cmd_no_fail ip rule del l3mdev priority 1000
@@ -65,6 +71,7 @@ cleanup() {
     fi
 
     # WAN status files
+    debug "Cleaning WAN status file on exit"
     while read PROVIDER ETHERNET WEIGHT PING_IPS; do
         clear_wan_status "$PROVIDER"
     done <<<"$WAN_CONF"
@@ -76,22 +83,26 @@ trap_pid
 trap cleanup INT TERM
 
 
+# VOID setup_vrf_tables(VOID): VOID
 # creat VRF tables
 setup_vrf_tables() {
     while read PROVIDER ETHERNET WEIGHT PING_IPS; do
         local TABLE_NAME=${PROVIDER,,}
         if ! grep -wq "${TABLE_NAME}\$" <<<"$RT_TABLES"; then
             local RT_TABLE="/etc/iproute2/rt_tables.d/${TABLE_NAME}.conf"
-            local NEW_TABLE=$(next_rt_table)
-            echo -e "${NEW_TABLE}\t${TABLE_NAME}" >"$RT_TABLE"
+            local TABLE_INDEX=$(next_rt_table)
+            echo -e "${TABLE_INDEX}\t${TABLE_NAME}" >"$RT_TABLE"
             RT_TABLES=$(read_rt_tables)
         fi
     done <<<"$WAN_CONF"
 }
 
 
+# VOID vrf_dhclient(VOID): VOID
+# run dhcp client for ETHERNET under VRF
 vrf_dhclient() {
     get_template 'dhclient.conf' >"$LEASE_CONF"
+    set_eth_stats "$ETHERNET"
     cmd ip vrf exec "$TABLE_NAME" \
         dhclient \
             -cf "$LEASE_CONF" \
@@ -100,6 +111,7 @@ vrf_dhclient() {
             "$ETHERNET"
 }
 
+# VOID migrate_to_vrf(VOID): VOID
 # enslave interfaces to VRF
 migrate_to_vrf() {
     cmd_no_fail ip rule add l3mdev priority 1000
@@ -143,6 +155,7 @@ migrate_to_vrf() {
 }
 
 
+# VOID forward_and_masq(VOID): VOID
 # enable IP forwarding and NAT
 forward_and_masq() {
     local INTERFACES=$(awk '{ print $2 }' <<<"$WAN_CONF")
@@ -175,20 +188,21 @@ forward_and_masq() {
         fi
 
         # masquerade from every interfaces
-        for INT in $LAN_INT $INTERFACES; do
-            log "Natting interface ${INT}${LAN_NET:+ from $LAN_NET}"
+        for INT in $INTERFACES; do
+            log "Natting interface ${INT}${LAN_NET:+" from $LAN_NET"}"
             local RULE="POSTROUTING ${LAN_NET:+-s $LAN_NET} -o $INT -j MASQUERADE"
-            ( iptables-save -t nat | grep -q -- "$RULE" ) || iptables -t nat -A $RULE
+            ( iptables-save -t nat | grep -q -- "$RULE" ) || cmd iptables -t nat -A $RULE
             if bool "$IPV6"; then
                 RULE="POSTROUTING -o $INT -j MASQUERADE"
-                ( ip6tables-save -t nat | grep -q -- "$RULE" ) || ip6tables -t nat -A $RULE
+                ( ip6tables-save -t nat | grep -q -- "$RULE" ) || cmd ip6tables -t nat -A $RULE
             fi
         done
     fi
 }
 
 
-# ping with ethernet binding and return RTTs if succeded
+# INT rtt_ping(PROVIDER, TARGET): RTT
+# stdout RTT of TARGET ping under PROVIDER VRF
 rtt_ping() {
     local PROVIDER=$1
     local TARGET=$2
@@ -197,7 +211,8 @@ rtt_ping() {
 }
 
 
-# write status file based on reachability
+# VOID check_connectivity(PROVIDER, TARGETS): VOID
+# write PROVIDER status file based on TARGETS reachability
 check_connectivity() {
     local PROVIDER=$1
     local TARGETS=$2
@@ -238,20 +253,34 @@ check_connectivity() {
 }
 
 
-main() {
+# VOID run(VOID): VOID
+# main function
+run() {
+    declare -A OLD_GATEWAY
+    declare -A OLD_ROUTES
+
     set_status 'RUNNING'
     while sleep $CHECK_INTERVAL; do
         while read PROVIDER ETHERNET WEIGHT PING_IPS; do
             local TABLE_NAME=${PROVIDER,,}
-            local GATEWAY=$(ip -4 route show default dev "$ETHERNET" table "$TABLE_NAME" | awk '{ print $3 }')
+            local ROUTES=$(ip -4 route show table "$TABLE_NAME")
+            local GATEWAY=$(awk '/^default/{ print $3 }' <<<"$ROUTES")
             if [[ -z "$GATEWAY" ]]; then
-                # FIXME: sometimes the default gateway disappear...
+                # FIXME: sometimes the default gateway disappear... why?
                 local LEASE_FILE="${RUNSTATEDIR}/dhclient.${ETHERNET}.leases"
                 local LEASE=$(get_last_lease "$LEASE_FILE")
                 local LEASE_OPTIONS=$(get_lease_options "$LEASE")
                 GATEWAY=$(awk -F= '/routers/{ print $2 }' <<<"$LEASE_OPTIONS")
+                [[ "$GATEWAY" != "${OLD_GATEWAY[$PROVIDER]}" || "$ROUTES" != "${OLD_ROUTES[$PROVIDER]}" ]] || continue
                 log "Reapply default route for ${PROVIDER} via ${GATEWAY}"
-                cmd_no_fail ip route add default via "$GATEWAY" dev "$ETHERNET" table "$TABLE_NAME"
+                if cmd ip route add default via "$GATEWAY" dev "$ETHERNET" table "$TABLE_NAME"; then
+                    unset OLD_GATEWAY[$PROVIDER]
+                    unset OLD_ROUTES[$PROVIDER]
+                else
+                    warn "$ROUTES"
+                    OLD_GATEWAY[$PROVIDER]="$GATEWAY"
+                    OLD_ROUTES[$PROVIDER]="$ROUTES"
+                fi
             fi
             check_connectivity $PROVIDER $PING_IPS &
         done <<<"$WAN_CONF"
@@ -260,5 +289,5 @@ main() {
 
 
 setup
-main
+run
 cleanup
